### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
freeze_vision_tower: true
deepspeed: examples/deepspeed/ds_z2_config.json
gradient_checkpointing: true

### dataset
dataset: mat_train
template: qwen2_vl
cutoff_len: 10240
max_samples: 100000000
overwrite_cache: false
preprocessing_num_workers: 1
dataloader_num_workers: 1
# lazy_preprocess: true


### output
output_dir: /share/data/drive_5/heakl/MAT-Agent/checkpoints/mat_v1
logging_steps: 1
save_steps: 1000000
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb 
save_total_limit: 1


### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 7.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
adam_beta2: 0.95

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
